version: "3.9"
networks:
  roboshop:
    driver: bridge
volumes:
  mysql:
    driver: local
    driver_opts:
       o: bind
       type: none
       device: /home/ec2-user/mysql
  mongodb:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/ec2-user/mongodb
  rabbitmq:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/ec2-user/rabbitmq
  redis:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/ec2-user/redis
services:
  web:
    image: raman89/web:v1
    container_name: web
    ports:
      - "80:80"
    depends_on:
      - catalogue
      - user
      - cart
      - shipping
      - mysql
  mongodb:
    image: raman89/mongodb:v1
    container_name: mongodb
    volumes:
      - mongodb:/data/db
  catalogue:
    image: raman89/catalogue:v1
    container_name: catalogue
    depends_on:
      - mongodb
  redis:
    image: redis
    container_name: redis
    volumes:
      - redis:/data
  user:
    image: raman89/user:v1
    container_name: user
    depends_on:
      - mongodb
      - redis
  cart:
    image: raman89/cart:v1
    container_name: cart
    depends_on:
    - redis
    - catalogue
  mysql:
    image: raman89/mysql:v1
    container_name: mysql
    volumes:
      - mysql:/var/lib/mysql
  shipping:
    image: raman89/shipping:v1
    container_name: shipping
    depends_on:
    - mysql
  rabbitmq:
    image: rabbitmq
    container_name: rabbitmq
    volumes:
      - rabbitmq
  payment:
    image: raman89/payment:v1
    container_name: payment
    depends_on:
    - rabbitmq
  ratings:
    image: raman89/ratings:v1
    container_name: ratings
    depends_on:
    - mysql